apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-real-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-real-app
  template:
    metadata:
      labels:
        app: eks-real-app
    spec:
      containers:
      - name: eks-real-app
        image: 202264954934.dkr.ecr.ap-south-1.amazonaws.com/eks-real-app:latest
        ports:
        - containerPort: 3000
