apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-real-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-real-app
  template:
    metadata:
      labels:
        app: eks-real-app
    spec:
      containers:
      - name: eks-real-app
        image: REPLACE_WITH_ECR_URI:latest
        ports:
        - containerPort: 3000
